### ISSUE TITLE
Cloudinary upgrade

### ISSUE THREAD

**Issue by pesseyjulien** [Speicher210/CloudinaryBundle#11]
Hi,

Any plan to upgrade the cloudinary dependency ?

Thanks,
Julien

**Comment by dragosprotung** [comment]
Hi,

what dependencies are you referring to ?

**Comment by pesseyjulien** [comment]
Hi,

Thanks for the quick reply.

The package.json dependency : "cloudinary/cloudinary_php": "^1.1"

They are on 1.20 now (https://packagist.org/packages/cloudinary/cloudinary_php) , maybe we could benefit from some few fix/improvements.

**Comment by dragosprotung** [comment]
That is the minimum required. You can use any version that satisfy the `^1.1` constraint. This includes `1.20`.

See [https://getcomposer.org/doc/articles/versions.md#caret-version-range-](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) for more information.

There will be a new version once `cloudinary/cloudinary_php` version `2.0` will be released.

**Comment by pesseyjulien** [comment]
alright, got it ! 

Thanks !
